version: '3'
services:
  app:
    build: .
    ports:
      - 50001:50000
    restart: always
    depends_on:
      - db-primary
  db-primary:
    build: ./db
    command: 
      - --replSet
      - rs0
      - --keyFile
      - /data/key/key
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    depends_on:
      - db-secondary
      - db-arbiter
  db-secondary:
    build: ./db
    command: 
      - --replSet
      - rs0
      - --keyFile
      - /data/key/key
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
  db-arbiter:
    build: ./db
    command: 
      - --replSet
      - rs0
      - --keyFile
      - /data/key/key
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
