version: '3'
services:
  app:
    build: .
    ports:
      - 50000:50000
    restart: always
  db-primary:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
