// Config

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: fairtreat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ############
// Enum
// ############
type BILL_CHANGE_TYPE int32

const (
	BILL_CHANGE_TYPE_GUEST   BILL_CHANGE_TYPE = 0 // 明細にユーザが増えた時
	BILL_CHANGE_TYPE_ITEM    BILL_CHANGE_TYPE = 1 // アイテムを支払う人が変更された時
	BILL_CHANGE_TYPE_CONFIRM BILL_CHANGE_TYPE = 2 // 明細が確定された時
)

// Enum value maps for BILL_CHANGE_TYPE.
var (
	BILL_CHANGE_TYPE_name = map[int32]string{
		0: "GUEST",
		1: "ITEM",
		2: "CONFIRM",
	}
	BILL_CHANGE_TYPE_value = map[string]int32{
		"GUEST":   0,
		"ITEM":    1,
		"CONFIRM": 2,
	}
)

func (x BILL_CHANGE_TYPE) Enum() *BILL_CHANGE_TYPE {
	p := new(BILL_CHANGE_TYPE)
	*p = x
	return p
}

func (x BILL_CHANGE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BILL_CHANGE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_fairtreat_proto_enumTypes[0].Descriptor()
}

func (BILL_CHANGE_TYPE) Type() protoreflect.EnumType {
	return &file_fairtreat_proto_enumTypes[0]
}

func (x BILL_CHANGE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BILL_CHANGE_TYPE.Descriptor instead.
func (BILL_CHANGE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{0}
}

// ############
// Types
// ############
type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host   *User   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Guests []*User `protobuf:"bytes,3,rep,name=guests,proto3" json:"guests,omitempty"`
	Items  []*Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bill) GetHost() *User {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Bill) GetGuests() []*User {
	if x != nil {
		return x.Guests
	}
	return nil
}

func (x *Bill) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price  int32   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Owners []*User `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetOwners() []*User {
	if x != nil {
		return x.Owners
	}
	return nil
}

type PayPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Price int32 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *PayPrice) Reset() {
	*x = PayPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPrice) ProtoMessage() {}

func (x *PayPrice) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPrice.ProtoReflect.Descriptor instead.
func (*PayPrice) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{3}
}

func (x *PayPrice) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PayPrice) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// ############
// Messages
// ############
// // Bill
// CreateBill
type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName string  `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Items    []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBillRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *CreateBillRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId string `protobuf:"bytes,1,opt,name=billId,proto3" json:"billId,omitempty"`
	Host   *User  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *CreateBillResponse) Reset() {
	*x = CreateBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillResponse) ProtoMessage() {}

func (x *CreateBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillResponse.ProtoReflect.Descriptor instead.
func (*CreateBillResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBillResponse) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *CreateBillResponse) GetHost() *User {
	if x != nil {
		return x.Host
	}
	return nil
}

// GetBill
type GetBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBillRequest) Reset() {
	*x = GetBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillRequest) ProtoMessage() {}

func (x *GetBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillRequest.ProtoReflect.Descriptor instead.
func (*GetBillRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{6}
}

func (x *GetBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *GetBillResponse) Reset() {
	*x = GetBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillResponse) ProtoMessage() {}

func (x *GetBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillResponse.ProtoReflect.Descriptor instead.
func (*GetBillResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{7}
}

func (x *GetBillResponse) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

// ConnectBill
type ConnectBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostName string `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
}

func (x *ConnectBillRequest) Reset() {
	*x = ConnectBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBillRequest) ProtoMessage() {}

func (x *ConnectBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBillRequest.ProtoReflect.Descriptor instead.
func (*ConnectBillRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectBillRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type ConnectBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type BILL_CHANGE_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=fairtreat.BILL_CHANGE_TYPE" json:"type,omitempty"`
	Id   int32            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // type => {GUEST: 0, ITEM: itemId, COMFIRM: 0}
}

func (x *ConnectBillResponse) Reset() {
	*x = ConnectBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBillResponse) ProtoMessage() {}

func (x *ConnectBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBillResponse.ProtoReflect.Descriptor instead.
func (*ConnectBillResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectBillResponse) GetType() BILL_CHANGE_TYPE {
	if x != nil {
		return x.Type
	}
	return BILL_CHANGE_TYPE_GUEST
}

func (x *ConnectBillResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ConfirmBill
type ConfirmBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConfirmBillRequest) Reset() {
	*x = ConfirmBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBillRequest) ProtoMessage() {}

func (x *ConfirmBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBillRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBillRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ConfirmBillResponse) Reset() {
	*x = ConfirmBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBillResponse) ProtoMessage() {}

func (x *ConfirmBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBillResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBillResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmBillResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// GetConfirmBill
type GetConfirmBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetConfirmBillRequest) Reset() {
	*x = GetConfirmBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfirmBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfirmBillRequest) ProtoMessage() {}

func (x *GetConfirmBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfirmBillRequest.ProtoReflect.Descriptor instead.
func (*GetConfirmBillRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfirmBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetConfirmBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count     int32       `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	PayPrices []*PayPrice `protobuf:"bytes,2,rep,name=payPrices,proto3" json:"payPrices,omitempty"`
}

func (x *GetConfirmBillResponse) Reset() {
	*x = GetConfirmBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfirmBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfirmBillResponse) ProtoMessage() {}

func (x *GetConfirmBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfirmBillResponse.ProtoReflect.Descriptor instead.
func (*GetConfirmBillResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfirmBillResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetConfirmBillResponse) GetPayPrices() []*PayPrice {
	if x != nil {
		return x.PayPrices
	}
	return nil
}

// // User
// Add
type AddUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{14}
}

func (x *AddUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Guest  *User `protobuf:"bytes,2,opt,name=guest,proto3" json:"guest,omitempty"` // userId取得できるように
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{15}
}

func (x *AddUserResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AddUserResponse) GetGuest() *User {
	if x != nil {
		return x.Guest
	}
	return nil
}

// Get
type GetUsersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUsersListRequest) Reset() {
	*x = GetUsersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersListRequest) ProtoMessage() {}

func (x *GetUsersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersListRequest.ProtoReflect.Descriptor instead.
func (*GetUsersListRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUsersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *GetUsersListResponse) Reset() {
	*x = GetUsersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersListResponse) ProtoMessage() {}

func (x *GetUsersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersListResponse.ProtoReflect.Descriptor instead.
func (*GetUsersListResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{17}
}

func (x *GetUsersListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetUsersListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// // Item
// GetList
type GetItemsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetItemsListRequest) Reset() {
	*x = GetItemsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsListRequest) ProtoMessage() {}

func (x *GetItemsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsListRequest.ProtoReflect.Descriptor instead.
func (*GetItemsListRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{18}
}

func (x *GetItemsListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Items []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetItemsListResponse) Reset() {
	*x = GetItemsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsListResponse) ProtoMessage() {}

func (x *GetItemsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsListResponse.ProtoReflect.Descriptor instead.
func (*GetItemsListResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{19}
}

func (x *GetItemsListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetItemsListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// / Owner
// Set
type SetItemOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId int32   `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Owners []*User `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *SetItemOwnerRequest) Reset() {
	*x = SetItemOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemOwnerRequest) ProtoMessage() {}

func (x *SetItemOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemOwnerRequest.ProtoReflect.Descriptor instead.
func (*SetItemOwnerRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{20}
}

func (x *SetItemOwnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetItemOwnerRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SetItemOwnerRequest) GetOwners() []*User {
	if x != nil {
		return x.Owners
	}
	return nil
}

type SetItemOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetItemOwnerResponse) Reset() {
	*x = SetItemOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemOwnerResponse) ProtoMessage() {}

func (x *SetItemOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemOwnerResponse.ProtoReflect.Descriptor instead.
func (*SetItemOwnerResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{21}
}

func (x *SetItemOwnerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Get
type GetItemOwnersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId int32  `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *GetItemOwnersRequest) Reset() {
	*x = GetItemOwnersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemOwnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemOwnersRequest) ProtoMessage() {}

func (x *GetItemOwnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemOwnersRequest.ProtoReflect.Descriptor instead.
func (*GetItemOwnersRequest) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{22}
}

func (x *GetItemOwnersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemOwnersRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetItemOwnersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count  int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Owners []*User `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *GetItemOwnersResponse) Reset() {
	*x = GetItemOwnersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fairtreat_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemOwnersResponse) ProtoMessage() {}

func (x *GetItemOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fairtreat_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemOwnersResponse.ProtoReflect.Descriptor instead.
func (*GetItemOwnersResponse) Descriptor() ([]byte, []int) {
	return file_fairtreat_proto_rawDescGZIP(), []int{23}
}

func (x *GetItemOwnersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetItemOwnersResponse) GetOwners() []*User {
	if x != nil {
		return x.Owners
	}
	return nil
}

var File_fairtreat_proto protoreflect.FileDescriptor

var file_fairtreat_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x22, 0x8b, 0x01, 0x0a,
	0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69,
	0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2a, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x69, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74,
	0x72, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x22, 0x45, 0x0a, 0x08, 0x50, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61,
	0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x56, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74,
	0x72, 0x65, 0x61, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x51, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66,
	0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65,
	0x61, 0x74, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x40, 0x0a,
	0x12, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x56, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74,
	0x2e, 0x42, 0x49, 0x4c, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a,
	0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x27, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74,
	0x72, 0x65, 0x61, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x09, 0x70,
	0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74,
	0x72, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x25, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x66, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72,
	0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x22, 0x2e, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x3e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x22, 0x56, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x27, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x2a, 0x34, 0x0a, 0x10, 0x42, 0x49, 0x4c, 0x4c,
	0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x09, 0x0a, 0x05,
	0x47, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x54, 0x45, 0x4d, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x10, 0x02, 0x32, 0xab,
	0x06, 0x0a, 0x09, 0x46, 0x61, 0x69, 0x72, 0x54, 0x72, 0x65, 0x61, 0x74, 0x12, 0x4b, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1c, 0x2e, 0x66, 0x61, 0x69,
	0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74,
	0x72, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1d, 0x2e, 0x66,
	0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x61,
	0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x4e, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1d,
	0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x57, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c,
	0x6c, 0x12, 0x20, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e,
	0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x66,
	0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66,
	0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1e, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x12,
	0x1e, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x58, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74, 0x72,
	0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x74,
	0x72, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a,
	0x66, 0x61, 0x69, 0x72, 0x74, 0x72, 0x65, 0x61, 0x74, 0x2e, 0x73, 0x75, 0x77, 0x61, 0x67, 0x65,
	0x65, 0x6b, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fairtreat_proto_rawDescOnce sync.Once
	file_fairtreat_proto_rawDescData = file_fairtreat_proto_rawDesc
)

func file_fairtreat_proto_rawDescGZIP() []byte {
	file_fairtreat_proto_rawDescOnce.Do(func() {
		file_fairtreat_proto_rawDescData = protoimpl.X.CompressGZIP(file_fairtreat_proto_rawDescData)
	})
	return file_fairtreat_proto_rawDescData
}

var file_fairtreat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fairtreat_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_fairtreat_proto_goTypes = []interface{}{
	(BILL_CHANGE_TYPE)(0),          // 0: fairtreat.BILL_CHANGE_TYPE
	(*Bill)(nil),                   // 1: fairtreat.Bill
	(*User)(nil),                   // 2: fairtreat.User
	(*Item)(nil),                   // 3: fairtreat.Item
	(*PayPrice)(nil),               // 4: fairtreat.PayPrice
	(*CreateBillRequest)(nil),      // 5: fairtreat.CreateBillRequest
	(*CreateBillResponse)(nil),     // 6: fairtreat.CreateBillResponse
	(*GetBillRequest)(nil),         // 7: fairtreat.GetBillRequest
	(*GetBillResponse)(nil),        // 8: fairtreat.GetBillResponse
	(*ConnectBillRequest)(nil),     // 9: fairtreat.ConnectBillRequest
	(*ConnectBillResponse)(nil),    // 10: fairtreat.ConnectBillResponse
	(*ConfirmBillRequest)(nil),     // 11: fairtreat.ConfirmBillRequest
	(*ConfirmBillResponse)(nil),    // 12: fairtreat.ConfirmBillResponse
	(*GetConfirmBillRequest)(nil),  // 13: fairtreat.GetConfirmBillRequest
	(*GetConfirmBillResponse)(nil), // 14: fairtreat.GetConfirmBillResponse
	(*AddUserRequest)(nil),         // 15: fairtreat.AddUserRequest
	(*AddUserResponse)(nil),        // 16: fairtreat.AddUserResponse
	(*GetUsersListRequest)(nil),    // 17: fairtreat.GetUsersListRequest
	(*GetUsersListResponse)(nil),   // 18: fairtreat.GetUsersListResponse
	(*GetItemsListRequest)(nil),    // 19: fairtreat.GetItemsListRequest
	(*GetItemsListResponse)(nil),   // 20: fairtreat.GetItemsListResponse
	(*SetItemOwnerRequest)(nil),    // 21: fairtreat.SetItemOwnerRequest
	(*SetItemOwnerResponse)(nil),   // 22: fairtreat.SetItemOwnerResponse
	(*GetItemOwnersRequest)(nil),   // 23: fairtreat.GetItemOwnersRequest
	(*GetItemOwnersResponse)(nil),  // 24: fairtreat.GetItemOwnersResponse
}
var file_fairtreat_proto_depIdxs = []int32{
	2,  // 0: fairtreat.Bill.host:type_name -> fairtreat.User
	2,  // 1: fairtreat.Bill.guests:type_name -> fairtreat.User
	3,  // 2: fairtreat.Bill.items:type_name -> fairtreat.Item
	2,  // 3: fairtreat.Item.owners:type_name -> fairtreat.User
	2,  // 4: fairtreat.PayPrice.user:type_name -> fairtreat.User
	3,  // 5: fairtreat.CreateBillRequest.items:type_name -> fairtreat.Item
	2,  // 6: fairtreat.CreateBillResponse.host:type_name -> fairtreat.User
	1,  // 7: fairtreat.GetBillResponse.bill:type_name -> fairtreat.Bill
	0,  // 8: fairtreat.ConnectBillResponse.type:type_name -> fairtreat.BILL_CHANGE_TYPE
	4,  // 9: fairtreat.GetConfirmBillResponse.payPrices:type_name -> fairtreat.PayPrice
	2,  // 10: fairtreat.AddUserResponse.guest:type_name -> fairtreat.User
	2,  // 11: fairtreat.GetUsersListResponse.users:type_name -> fairtreat.User
	3,  // 12: fairtreat.GetItemsListResponse.items:type_name -> fairtreat.Item
	2,  // 13: fairtreat.SetItemOwnerRequest.owners:type_name -> fairtreat.User
	2,  // 14: fairtreat.GetItemOwnersResponse.owners:type_name -> fairtreat.User
	5,  // 15: fairtreat.FairTreat.CreateBill:input_type -> fairtreat.CreateBillRequest
	7,  // 16: fairtreat.FairTreat.GetBill:input_type -> fairtreat.GetBillRequest
	9,  // 17: fairtreat.FairTreat.ConnectBill:input_type -> fairtreat.ConnectBillRequest
	11, // 18: fairtreat.FairTreat.ConfirmBill:input_type -> fairtreat.ConfirmBillRequest
	13, // 19: fairtreat.FairTreat.GetConfirmBill:input_type -> fairtreat.GetConfirmBillRequest
	15, // 20: fairtreat.FairTreat.AddUser:input_type -> fairtreat.AddUserRequest
	17, // 21: fairtreat.FairTreat.GetUsersList:input_type -> fairtreat.GetUsersListRequest
	19, // 22: fairtreat.FairTreat.GetItemsList:input_type -> fairtreat.GetItemsListRequest
	21, // 23: fairtreat.FairTreat.SetOwners:input_type -> fairtreat.SetItemOwnerRequest
	23, // 24: fairtreat.FairTreat.GetItemOwnersList:input_type -> fairtreat.GetItemOwnersRequest
	6,  // 25: fairtreat.FairTreat.CreateBill:output_type -> fairtreat.CreateBillResponse
	8,  // 26: fairtreat.FairTreat.GetBill:output_type -> fairtreat.GetBillResponse
	10, // 27: fairtreat.FairTreat.ConnectBill:output_type -> fairtreat.ConnectBillResponse
	12, // 28: fairtreat.FairTreat.ConfirmBill:output_type -> fairtreat.ConfirmBillResponse
	14, // 29: fairtreat.FairTreat.GetConfirmBill:output_type -> fairtreat.GetConfirmBillResponse
	16, // 30: fairtreat.FairTreat.AddUser:output_type -> fairtreat.AddUserResponse
	18, // 31: fairtreat.FairTreat.GetUsersList:output_type -> fairtreat.GetUsersListResponse
	20, // 32: fairtreat.FairTreat.GetItemsList:output_type -> fairtreat.GetItemsListResponse
	22, // 33: fairtreat.FairTreat.SetOwners:output_type -> fairtreat.SetItemOwnerResponse
	24, // 34: fairtreat.FairTreat.GetItemOwnersList:output_type -> fairtreat.GetItemOwnersResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_fairtreat_proto_init() }
func file_fairtreat_proto_init() {
	if File_fairtreat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fairtreat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfirmBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfirmBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemOwnersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fairtreat_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemOwnersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fairtreat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fairtreat_proto_goTypes,
		DependencyIndexes: file_fairtreat_proto_depIdxs,
		EnumInfos:         file_fairtreat_proto_enumTypes,
		MessageInfos:      file_fairtreat_proto_msgTypes,
	}.Build()
	File_fairtreat_proto = out.File
	file_fairtreat_proto_rawDesc = nil
	file_fairtreat_proto_goTypes = nil
	file_fairtreat_proto_depIdxs = nil
}
