version: '3'
services:
  dev:
    build: ./go
    command: sleep infinity
    working_dir: /work
    volumes:
      - ../:/work:cached
      - ~/.ssh:/root/.ssh
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb