// Config

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: warikan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ############
// Enum
// ############
type BILL_CHANGE_TYPE int32

const (
	BILL_CHANGE_TYPE_OWNER BILL_CHANGE_TYPE = 0
	BILL_CHANGE_TYPE_GUEST BILL_CHANGE_TYPE = 1
	BILL_CHANGE_TYPE_BILL  BILL_CHANGE_TYPE = 2
	BILL_CHANGE_TYPE_ITEM  BILL_CHANGE_TYPE = 3
)

// Enum value maps for BILL_CHANGE_TYPE.
var (
	BILL_CHANGE_TYPE_name = map[int32]string{
		0: "OWNER",
		1: "GUEST",
		2: "BILL",
		3: "ITEM",
	}
	BILL_CHANGE_TYPE_value = map[string]int32{
		"OWNER": 0,
		"GUEST": 1,
		"BILL":  2,
		"ITEM":  3,
	}
)

func (x BILL_CHANGE_TYPE) Enum() *BILL_CHANGE_TYPE {
	p := new(BILL_CHANGE_TYPE)
	*p = x
	return p
}

func (x BILL_CHANGE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BILL_CHANGE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_warikan_proto_enumTypes[0].Descriptor()
}

func (BILL_CHANGE_TYPE) Type() protoreflect.EnumType {
	return &file_warikan_proto_enumTypes[0]
}

func (x BILL_CHANGE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BILL_CHANGE_TYPE.Descriptor instead.
func (BILL_CHANGE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{0}
}

// ############
// Types
// ############
type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password string  `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Host     *User   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Guests   []*User `protobuf:"bytes,4,rep,name=guests,proto3" json:"guests,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bill) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Bill) GetHost() *User {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Bill) GetGuests() []*User {
	if x != nil {
		return x.Guests
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount int32   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Price  int32   `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Owners []*User `protobuf:"bytes,5,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetOwners() []*User {
	if x != nil {
		return x.Owners
	}
	return nil
}

// ############
// Messages
// ############
// // Bill
// CreateBill
type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *User `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBillRequest) GetHost() *User {
	if x != nil {
		return x.Host
	}
	return nil
}

type CreateBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill          *Bill  `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	OwnerPassword string `protobuf:"bytes,2,opt,name=ownerPassword,proto3" json:"ownerPassword,omitempty"`
}

func (x *CreateBillResponse) Reset() {
	*x = CreateBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillResponse) ProtoMessage() {}

func (x *CreateBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillResponse.ProtoReflect.Descriptor instead.
func (*CreateBillResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBillResponse) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *CreateBillResponse) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

// ConnectBill
type ConnectBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *ConnectBillRequest) Reset() {
	*x = ConnectBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBillRequest) ProtoMessage() {}

func (x *ConnectBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBillRequest.ProtoReflect.Descriptor instead.
func (*ConnectBillRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectBillRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type ConnectBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type BILL_CHANGE_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=warikan.BILL_CHANGE_TYPE" json:"type,omitempty"`
	Id   int32            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConnectBillResponse) Reset() {
	*x = ConnectBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBillResponse) ProtoMessage() {}

func (x *ConnectBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBillResponse.ProtoReflect.Descriptor instead.
func (*ConnectBillResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectBillResponse) GetType() BILL_CHANGE_TYPE {
	if x != nil {
		return x.Type
	}
	return BILL_CHANGE_TYPE_OWNER
}

func (x *ConnectBillResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ConfirmBill
type ConfirmBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill          *Bill  `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	OwnerPassword string `protobuf:"bytes,2,opt,name=ownerPassword,proto3" json:"ownerPassword,omitempty"`
}

func (x *ConfirmBillRequest) Reset() {
	*x = ConfirmBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBillRequest) ProtoMessage() {}

func (x *ConfirmBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBillRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBillRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmBillRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *ConfirmBillRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

type ConfirmBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ConfirmBillResponse) Reset() {
	*x = ConfirmBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBillResponse) ProtoMessage() {}

func (x *ConfirmBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBillResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBillResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmBillResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// // User
// Add
type AddUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{9}
}

func (x *AddUserRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *AddUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AddUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{10}
}

func (x *AddUserResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Remove
type RemoveUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill         *Bill  `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	HostPassword string `protobuf:"bytes,2,opt,name=hostPassword,proto3" json:"hostPassword,omitempty"`
	UserId       int32  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveUserRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *RemoveUserRequest) GetHostPassword() string {
	if x != nil {
		return x.HostPassword
	}
	return ""
}

func (x *RemoveUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveUserResponse) Reset() {
	*x = RemoveUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserResponse) ProtoMessage() {}

func (x *RemoveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveUserResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Get
type GetUsersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *GetUsersListRequest) Reset() {
	*x = GetUsersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersListRequest) ProtoMessage() {}

func (x *GetUsersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersListRequest.ProtoReflect.Descriptor instead.
func (*GetUsersListRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{13}
}

func (x *GetUsersListRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type GetUsersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *GetUsersListResponse) Reset() {
	*x = GetUsersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersListResponse) ProtoMessage() {}

func (x *GetUsersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersListResponse.ProtoReflect.Descriptor instead.
func (*GetUsersListResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{14}
}

func (x *GetUsersListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetUsersListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// // Item
// Set
type SetItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill          *Bill   `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	OwnerPassword string  `protobuf:"bytes,2,opt,name=ownerPassword,proto3" json:"ownerPassword,omitempty"`
	Items         []*Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SetItemRequest) Reset() {
	*x = SetItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemRequest) ProtoMessage() {}

func (x *SetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemRequest.ProtoReflect.Descriptor instead.
func (*SetItemRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{15}
}

func (x *SetItemRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *SetItemRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

func (x *SetItemRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetItemResponse) Reset() {
	*x = SetItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemResponse) ProtoMessage() {}

func (x *SetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemResponse.ProtoReflect.Descriptor instead.
func (*SetItemResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{16}
}

func (x *SetItemResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Add
type AddItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill          *Bill  `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	OwnerPassword string `protobuf:"bytes,2,opt,name=ownerPassword,proto3" json:"ownerPassword,omitempty"`
	Item          *Item  `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{17}
}

func (x *AddItemRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *AddItemRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

func (x *AddItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{18}
}

func (x *AddItemResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Remove
type RemoveItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill          *Bill  `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	OwnerPassword string `protobuf:"bytes,2,opt,name=ownerPassword,proto3" json:"ownerPassword,omitempty"`
	ItemId        int32  `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveItemRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *RemoveItemRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

func (x *RemoveItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type RemoveItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveItemResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// GetList
type GetItemsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *GetItemsListRequest) Reset() {
	*x = GetItemsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsListRequest) ProtoMessage() {}

func (x *GetItemsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsListRequest.ProtoReflect.Descriptor instead.
func (*GetItemsListRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{21}
}

func (x *GetItemsListRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type GetItemsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Items []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetItemsListResponse) Reset() {
	*x = GetItemsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsListResponse) ProtoMessage() {}

func (x *GetItemsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsListResponse.ProtoReflect.Descriptor instead.
func (*GetItemsListResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{22}
}

func (x *GetItemsListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetItemsListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// Get
type GetItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill   *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	ItemId int32 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{23}
}

func (x *GetItemRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *GetItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{24}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// / Owner
// Set
type SetItemOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill         *Bill   `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	HostPassword string  `protobuf:"bytes,2,opt,name=hostPassword,proto3" json:"hostPassword,omitempty"`
	ItemId       int32   `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Owners       []*User `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *SetItemOwnerRequest) Reset() {
	*x = SetItemOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemOwnerRequest) ProtoMessage() {}

func (x *SetItemOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemOwnerRequest.ProtoReflect.Descriptor instead.
func (*SetItemOwnerRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{25}
}

func (x *SetItemOwnerRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *SetItemOwnerRequest) GetHostPassword() string {
	if x != nil {
		return x.HostPassword
	}
	return ""
}

func (x *SetItemOwnerRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SetItemOwnerRequest) GetOwners() []*User {
	if x != nil {
		return x.Owners
	}
	return nil
}

type SetItemOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetItemOwnerResponse) Reset() {
	*x = SetItemOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemOwnerResponse) ProtoMessage() {}

func (x *SetItemOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemOwnerResponse.ProtoReflect.Descriptor instead.
func (*SetItemOwnerResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{26}
}

func (x *SetItemOwnerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Add
type AddItemOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill   *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	ItemId int32 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Owner  *User `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *AddItemOwnerRequest) Reset() {
	*x = AddItemOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemOwnerRequest) ProtoMessage() {}

func (x *AddItemOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemOwnerRequest.ProtoReflect.Descriptor instead.
func (*AddItemOwnerRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{27}
}

func (x *AddItemOwnerRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *AddItemOwnerRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AddItemOwnerRequest) GetOwner() *User {
	if x != nil {
		return x.Owner
	}
	return nil
}

type AddItemOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddItemOwnerResponse) Reset() {
	*x = AddItemOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemOwnerResponse) ProtoMessage() {}

func (x *AddItemOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemOwnerResponse.ProtoReflect.Descriptor instead.
func (*AddItemOwnerResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{28}
}

func (x *AddItemOwnerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Remove
type RemoveItemOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill   *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	ItemId int32 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	UserId int32 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *RemoveItemOwnerRequest) Reset() {
	*x = RemoveItemOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemOwnerRequest) ProtoMessage() {}

func (x *RemoveItemOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemOwnerRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemOwnerRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveItemOwnerRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *RemoveItemOwnerRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RemoveItemOwnerRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveItemOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveItemOwnerResponse) Reset() {
	*x = RemoveItemOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemOwnerResponse) ProtoMessage() {}

func (x *RemoveItemOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemOwnerResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemOwnerResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveItemOwnerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// GetList
type GetItemOwnersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill   *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	ItemId int32 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *GetItemOwnersRequest) Reset() {
	*x = GetItemOwnersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemOwnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemOwnersRequest) ProtoMessage() {}

func (x *GetItemOwnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemOwnersRequest.ProtoReflect.Descriptor instead.
func (*GetItemOwnersRequest) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{31}
}

func (x *GetItemOwnersRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *GetItemOwnersRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetItemOwnersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count  int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Owners []*User `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *GetItemOwnersResponse) Reset() {
	*x = GetItemOwnersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warikan_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemOwnersResponse) ProtoMessage() {}

func (x *GetItemOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warikan_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemOwnersResponse.ProtoReflect.Descriptor instead.
func (*GetItemOwnersResponse) Descriptor() ([]byte, []int) {
	return file_warikan_proto_rawDescGZIP(), []int{32}
}

func (x *GetItemOwnersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetItemOwnersResponse) GetOwners() []*User {
	if x != nil {
		return x.Owners
	}
	return nil
}

var File_warikan_proto protoreflect.FileDescriptor

var file_warikan_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x22, 0x7c, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72,
	0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x06, 0x67, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x2a, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x7f, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x06,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77,
	0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x22, 0x36, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04,
	0x62, 0x69, 0x6c, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x37, 0x0a, 0x12, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62,
	0x69, 0x6c, 0x6c, 0x22, 0x54, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x69,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b,
	0x61, 0x6e, 0x2e, 0x42, 0x49, 0x4c, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x12, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69,
	0x6c, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x56, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61,
	0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x21, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72,
	0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x29, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x72, 0x0a, 0x11, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69,
	0x6c, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c,
	0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c,
	0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x51, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x7e, 0x0a, 0x0e, 0x53, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62,
	0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69,
	0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x24,
	0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x29, 0x0a, 0x0f, 0x53, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x7c, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42,
	0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x21, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x22, 0x29, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x74, 0x0a,
	0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x38, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x51, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b,
	0x61, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4b,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62,
	0x69, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77,
	0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x9b, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61,
	0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x22, 0x0a, 0x0c,
	0x68, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b,
	0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x22,
	0x2e, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x75, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42,
	0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6b, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62,
	0x69, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77,
	0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b,
	0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x2a,
	0x3c, 0x0a, 0x10, 0x42, 0x49, 0x4c, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x47, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x49, 0x4c,
	0x4c, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x03, 0x32, 0xde, 0x08,
	0x0a, 0x07, 0x57, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x12, 0x47, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x69, 0x6c,
	0x6c, 0x12, 0x1b, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x4a, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x12,
	0x1b, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77,
	0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42, 0x69,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61,
	0x6e, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x72,
	0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x17, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x77, 0x61, 0x72, 0x69,
	0x6b, 0x61, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x17, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x77, 0x61, 0x72, 0x69,
	0x6b, 0x61, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c,
	0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77,
	0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b,
	0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a,
	0x09, 0x53, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x72,
	0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b,
	0x61, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x08, 0x41, 0x64, 0x64,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e,
	0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x41, 0x64,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e,
	0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77,
	0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1e,
	0x5a, 0x1c, 0x77, 0x61, 0x72, 0x69, 0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x75, 0x77, 0x61, 0x67, 0x65,
	0x65, 0x6b, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_warikan_proto_rawDescOnce sync.Once
	file_warikan_proto_rawDescData = file_warikan_proto_rawDesc
)

func file_warikan_proto_rawDescGZIP() []byte {
	file_warikan_proto_rawDescOnce.Do(func() {
		file_warikan_proto_rawDescData = protoimpl.X.CompressGZIP(file_warikan_proto_rawDescData)
	})
	return file_warikan_proto_rawDescData
}

var file_warikan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_warikan_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_warikan_proto_goTypes = []interface{}{
	(BILL_CHANGE_TYPE)(0),           // 0: warikan.BILL_CHANGE_TYPE
	(*Bill)(nil),                    // 1: warikan.Bill
	(*User)(nil),                    // 2: warikan.User
	(*Item)(nil),                    // 3: warikan.Item
	(*CreateBillRequest)(nil),       // 4: warikan.CreateBillRequest
	(*CreateBillResponse)(nil),      // 5: warikan.CreateBillResponse
	(*ConnectBillRequest)(nil),      // 6: warikan.ConnectBillRequest
	(*ConnectBillResponse)(nil),     // 7: warikan.ConnectBillResponse
	(*ConfirmBillRequest)(nil),      // 8: warikan.ConfirmBillRequest
	(*ConfirmBillResponse)(nil),     // 9: warikan.ConfirmBillResponse
	(*AddUserRequest)(nil),          // 10: warikan.AddUserRequest
	(*AddUserResponse)(nil),         // 11: warikan.AddUserResponse
	(*RemoveUserRequest)(nil),       // 12: warikan.RemoveUserRequest
	(*RemoveUserResponse)(nil),      // 13: warikan.RemoveUserResponse
	(*GetUsersListRequest)(nil),     // 14: warikan.GetUsersListRequest
	(*GetUsersListResponse)(nil),    // 15: warikan.GetUsersListResponse
	(*SetItemRequest)(nil),          // 16: warikan.SetItemRequest
	(*SetItemResponse)(nil),         // 17: warikan.SetItemResponse
	(*AddItemRequest)(nil),          // 18: warikan.AddItemRequest
	(*AddItemResponse)(nil),         // 19: warikan.AddItemResponse
	(*RemoveItemRequest)(nil),       // 20: warikan.RemoveItemRequest
	(*RemoveItemResponse)(nil),      // 21: warikan.RemoveItemResponse
	(*GetItemsListRequest)(nil),     // 22: warikan.GetItemsListRequest
	(*GetItemsListResponse)(nil),    // 23: warikan.GetItemsListResponse
	(*GetItemRequest)(nil),          // 24: warikan.GetItemRequest
	(*GetItemResponse)(nil),         // 25: warikan.GetItemResponse
	(*SetItemOwnerRequest)(nil),     // 26: warikan.SetItemOwnerRequest
	(*SetItemOwnerResponse)(nil),    // 27: warikan.SetItemOwnerResponse
	(*AddItemOwnerRequest)(nil),     // 28: warikan.AddItemOwnerRequest
	(*AddItemOwnerResponse)(nil),    // 29: warikan.AddItemOwnerResponse
	(*RemoveItemOwnerRequest)(nil),  // 30: warikan.RemoveItemOwnerRequest
	(*RemoveItemOwnerResponse)(nil), // 31: warikan.RemoveItemOwnerResponse
	(*GetItemOwnersRequest)(nil),    // 32: warikan.GetItemOwnersRequest
	(*GetItemOwnersResponse)(nil),   // 33: warikan.GetItemOwnersResponse
}
var file_warikan_proto_depIdxs = []int32{
	2,  // 0: warikan.Bill.host:type_name -> warikan.User
	2,  // 1: warikan.Bill.guests:type_name -> warikan.User
	2,  // 2: warikan.Item.owners:type_name -> warikan.User
	2,  // 3: warikan.CreateBillRequest.host:type_name -> warikan.User
	1,  // 4: warikan.CreateBillResponse.bill:type_name -> warikan.Bill
	1,  // 5: warikan.ConnectBillRequest.bill:type_name -> warikan.Bill
	0,  // 6: warikan.ConnectBillResponse.type:type_name -> warikan.BILL_CHANGE_TYPE
	1,  // 7: warikan.ConfirmBillRequest.bill:type_name -> warikan.Bill
	1,  // 8: warikan.AddUserRequest.bill:type_name -> warikan.Bill
	2,  // 9: warikan.AddUserRequest.user:type_name -> warikan.User
	1,  // 10: warikan.RemoveUserRequest.bill:type_name -> warikan.Bill
	1,  // 11: warikan.GetUsersListRequest.bill:type_name -> warikan.Bill
	2,  // 12: warikan.GetUsersListResponse.users:type_name -> warikan.User
	1,  // 13: warikan.SetItemRequest.bill:type_name -> warikan.Bill
	3,  // 14: warikan.SetItemRequest.items:type_name -> warikan.Item
	1,  // 15: warikan.AddItemRequest.bill:type_name -> warikan.Bill
	3,  // 16: warikan.AddItemRequest.item:type_name -> warikan.Item
	1,  // 17: warikan.RemoveItemRequest.bill:type_name -> warikan.Bill
	1,  // 18: warikan.GetItemsListRequest.bill:type_name -> warikan.Bill
	3,  // 19: warikan.GetItemsListResponse.items:type_name -> warikan.Item
	1,  // 20: warikan.GetItemRequest.bill:type_name -> warikan.Bill
	3,  // 21: warikan.GetItemResponse.item:type_name -> warikan.Item
	1,  // 22: warikan.SetItemOwnerRequest.bill:type_name -> warikan.Bill
	2,  // 23: warikan.SetItemOwnerRequest.owners:type_name -> warikan.User
	1,  // 24: warikan.AddItemOwnerRequest.bill:type_name -> warikan.Bill
	2,  // 25: warikan.AddItemOwnerRequest.owner:type_name -> warikan.User
	1,  // 26: warikan.RemoveItemOwnerRequest.bill:type_name -> warikan.Bill
	1,  // 27: warikan.GetItemOwnersRequest.bill:type_name -> warikan.Bill
	2,  // 28: warikan.GetItemOwnersResponse.owners:type_name -> warikan.User
	4,  // 29: warikan.Warikan.CreateBill:input_type -> warikan.CreateBillRequest
	6,  // 30: warikan.Warikan.ConnectBill:input_type -> warikan.ConnectBillRequest
	8,  // 31: warikan.Warikan.ConfirmBill:input_type -> warikan.ConfirmBillRequest
	10, // 32: warikan.Warikan.AddUser:input_type -> warikan.AddUserRequest
	12, // 33: warikan.Warikan.RemoveUser:input_type -> warikan.RemoveUserRequest
	14, // 34: warikan.Warikan.GetUsersList:input_type -> warikan.GetUsersListRequest
	16, // 35: warikan.Warikan.SetItems:input_type -> warikan.SetItemRequest
	18, // 36: warikan.Warikan.AddItem:input_type -> warikan.AddItemRequest
	20, // 37: warikan.Warikan.RemoveItem:input_type -> warikan.RemoveItemRequest
	22, // 38: warikan.Warikan.GetItemsList:input_type -> warikan.GetItemsListRequest
	24, // 39: warikan.Warikan.GetItem:input_type -> warikan.GetItemRequest
	26, // 40: warikan.Warikan.SetOwners:input_type -> warikan.SetItemOwnerRequest
	28, // 41: warikan.Warikan.AddOwner:input_type -> warikan.AddItemOwnerRequest
	30, // 42: warikan.Warikan.RemoveOwner:input_type -> warikan.RemoveItemOwnerRequest
	32, // 43: warikan.Warikan.GetItemOwnersList:input_type -> warikan.GetItemOwnersRequest
	5,  // 44: warikan.Warikan.CreateBill:output_type -> warikan.CreateBillResponse
	7,  // 45: warikan.Warikan.ConnectBill:output_type -> warikan.ConnectBillResponse
	9,  // 46: warikan.Warikan.ConfirmBill:output_type -> warikan.ConfirmBillResponse
	11, // 47: warikan.Warikan.AddUser:output_type -> warikan.AddUserResponse
	13, // 48: warikan.Warikan.RemoveUser:output_type -> warikan.RemoveUserResponse
	15, // 49: warikan.Warikan.GetUsersList:output_type -> warikan.GetUsersListResponse
	17, // 50: warikan.Warikan.SetItems:output_type -> warikan.SetItemResponse
	19, // 51: warikan.Warikan.AddItem:output_type -> warikan.AddItemResponse
	21, // 52: warikan.Warikan.RemoveItem:output_type -> warikan.RemoveItemResponse
	23, // 53: warikan.Warikan.GetItemsList:output_type -> warikan.GetItemsListResponse
	25, // 54: warikan.Warikan.GetItem:output_type -> warikan.GetItemResponse
	27, // 55: warikan.Warikan.SetOwners:output_type -> warikan.SetItemOwnerResponse
	29, // 56: warikan.Warikan.AddOwner:output_type -> warikan.AddItemOwnerResponse
	31, // 57: warikan.Warikan.RemoveOwner:output_type -> warikan.RemoveItemOwnerResponse
	33, // 58: warikan.Warikan.GetItemOwnersList:output_type -> warikan.GetItemOwnersResponse
	44, // [44:59] is the sub-list for method output_type
	29, // [29:44] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_warikan_proto_init() }
func file_warikan_proto_init() {
	if File_warikan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_warikan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemOwnersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warikan_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemOwnersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_warikan_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warikan_proto_goTypes,
		DependencyIndexes: file_warikan_proto_depIdxs,
		EnumInfos:         file_warikan_proto_enumTypes,
		MessageInfos:      file_warikan_proto_msgTypes,
	}.Build()
	File_warikan_proto = out.File
	file_warikan_proto_rawDesc = nil
	file_warikan_proto_goTypes = nil
	file_warikan_proto_depIdxs = nil
}
